apiVersion: v1
kind: Service
metadata:
  name: api-pelicula
  labels:
    app: api-pelicula
spec:
  ports:
    - port: 5000
      targetPort: http-server
  selector:
    app: api-pelicula
  type: LoadBalancer
